name: MSA integration test PR
on:
 pull_request:

jobs:
 run-databricks-notebook:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
     - name: Run a databricks notebook
       uses: databricks/run-notebook@v0
       with:
         local-notebook-path: RUNME.py
         git-commit: ${{ github.sha }}
         databricks-host: ${{ secrets.DEPLOYMENT_TARGET_URL_MSA }}
         databricks-token: ${{ secrets.DEPLOYMENT_TARGET_TOKEN_MSA }}
         new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "10.4.x-scala2.12",
             "node_type_id": "Standard_D3_v2",
             "azure_attributes": {
                            "availability": "ON_DEMAND_AZURE",
                            "first_on_demand": 1
                            }
           }
         notebook-params-json: >
           {
            "run_job": "True"
           }
